version: "3"
services:
  client:
    build:
      context: ./
      dockerfile: DEV.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:cached
      - client-node-modules:/app/node_modules/
volumes:
  client-node-modules: